### PR TITLE
update postgresql to v1.8.0

### LINKED ISSUE #847: bump up postgres operator
What can we help you?

### PR DESCRIPTION
**Pull request by bitsf**
fix #847

### CODE REVIEW

**Review by yxxhero — APPROVED** [review]
lgtm

**Review by cndoit18 — APPROVED** [review]
LGTM

**Comment by bitsf** [comment]
upgrading from lower version is breaking with this PR.

**Comment by MarcelMue** [comment]
> upgrading from lower version is breaking with this PR.

Currently we are using 1.7.0 - are you planning to pick up this PR again later @bitsf or should we close this?

**Comment by thcdrt** [comment]
Hello there,

What do we do about it finally ?

**Comment by MarcelMue** [comment]
This is very outdated by now. If you want to continue working on this, please re-open and update.

**Pull request closed without merging**
