### PR TITLE
fix registry s3 secret

### LINKED ISSUE #305: harbor-registry and harbor-registryctl pod can not running
What can we help you?

image

image

Maybe secret data field info is not correct.

### PR DESCRIPTION
**Pull request by bitsf**
close #305
fix registry s3 secret

### CODE REVIEW

**Review by steven-zou — APPROVED** [review]
LGTM

**Review by chlins — APPROVED** [review]
LGTM

**Comment by soulseen** [comment]
why not import `SharedSecretKey` directly?

**Review by soulseen — APPROVED** [review]
lgtm

**Pull request merged**
