### PR TITLE
GH-969: Support templateAnnotations per each component

### LINKED ISSUE #969: Feature request - Support custom annotations
**Is your feature request related to a problem? Please describe.**
Currently, the operator doesn't support injecting custom annotations.

**Describe the solution you'd like**
```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  # These annotations should be injected into all objects created by the operator
  annotations:
    foo: 'xyz'
spec:
  core:
    # These annotations should be injected only into core components
    annotations:
      bar: 'abc'
```

**Describe the main design/architecture of your solution**
Be able to define generic annotations that will be injected in all objects as well as custom annotations per component (core, registry, trivy, etc).

**Additional context**
We would like to configure **Monitor Prometheus metrics** with dynatrace so we need to annotate the pods who export metrics: exporter, core, jobservice, and registry.

```yaml
annotations:
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: '/path/to-metrics'
    metrics.dynatrace.com/port: '9001'
```

### PR DESCRIPTION
**Pull request by xoanmi**
Support custom template annotations to be added to each of the component deployment templates:

```yaml
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
spec:
  trivy:
    # These annotations will be injected only into core `.spec.template.metadata.annotations`
    templateAnnotations:
      foo: 'bar'
```

```bash
➜ k get deployment sample-harbor-harbor-trivy -o jsonpath='{.spec.template.metadata.annotations}' | jq
{
  "foo": "bar2",
  "goharbor.io/warning": "⚠️ This Resource is managed by *trivy* ⚠️",
  "sample-harbor-harbor-trivy.default.configmap.trivy.goharbor.io/uuid": "fc8e7dc9-e6ba-4434-ae38-5706e878696b",
  "sample-harbor-harbor-trivy.default.configmap.trivy.goharbor.io/version": "247114",
  "sample-harbor-harbor-trivy.default.secret.trivy.goharbor.io/uuid": "960626d1-f382-4843-990c-d3bc399d9029",
  "sample-harbor-harbor-trivy.default.secret.trivy.goharbor.io/version": "247115"
}
```

close #969 

Co-authored-by: Joan Miquel Luque Oliver <joan.luque@dynatrace.com>
Co-authored-by: Carlos Vega <carlos.vega@dynatrace.com>

Signed-off-by: Joan Miquel Luque Oliver <joan.luque@dynatrace.com>

### CODE REVIEW

**Comment by bitsf** [comment]
@xoanmi please run `make generated-diff-test` to fix ci

**Comment by xoanmi** [comment]
> @xoanmi please run `make generated-diff-test` to fix ci

Done ✅ 

```bash
$ make go-dependencies-test

...

nothing to commit, working tree clean
git diff --diff-filter=d --exit-code HEAD
```

```bash
make generated-diff-test

...

nothing to commit, working tree clean
git diff --diff-filter=d --exit-code HEAD
```

**Comment by xoanmi** [comment]
The failure on `Tests / Go tests (pull_request)` seems an unrelated connectivity issue:

```bash
• Failure [8.177 seconds]
NotaryServer
/home/runner/work/harbor-operator/harbor-operator/controllers/goharbor/notaryserver/notaryserver_test.go:23
  Without TLS
  /home/runner/work/harbor-operator/harbor-operator/controllers/goharbor/notaryserver/notaryserver_test.go:49
    Should works [It]
    /home/runner/work/harbor-operator/harbor-operator/controllers/goharbor/notaryserver/notaryserver_test.go:60

    Timed out after 1.036s.
    Unexpected error:
        <*errors.StatusError | 0xc0008568c0>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "error trying to reach service: dial tcp 10.244.2.32:4443: connect: connection refused",
                Reason: "ServiceUnavailable",
                Details: nil,
                Code: 503,
            },
        }
        error trying to reach service: dial tcp 10.244.2.32:4443: connect: connection refused
    occurred
```

@bitsf could you relaunch the test action please?

**Review by bitsf — APPROVED** [review]

**Review by heww — APPROVED** [review]

**Comment by xoanmi** [comment]
@bitsf @heww what is the procedure to get this PR merged and released?

**Pull request merged**
