### PR TITLE
upgrade controller-runtime version

### PR DESCRIPTION
**Pull request by CoderTH**
issue #1033

### CODE REVIEW

**Comment by thcdrt** [comment]
Hello,why closing it ?

**Comment by CoderTH** [comment]
> Hello, Why closing it ?

hello 
There are still some problems in the code, there is no time to do it in the first two days, so it is closed temporarily. I will repair these problems and then reopen this PR

**Comment by CoderTH** [comment]
@thcdrt hi 
can you help me run the ci pipeline ?

**Review by thcdrt — APPROVED** [review]
LGTM

**Comment by CoderTH** [comment]
@thcdrt i don't know why the`Generated files are up to date` and `chart K8S xxx` ci step error , can you take a look at it for me ？

**Comment by MarcelMue** [comment]
> @thcdrt i don't know why the`Generated files are up to date` and `chart K8S xxx` ci step error , can you take a look at it for me ？

There is a `generate` target in the makefile to generate all necessary files: https://github.com/goharbor/harbor-operator/blob/4cabfa9fc4a8692a3894640cc597fcf704a96d27/Makefile#L201-L202

**Comment by thcdrt** [comment]
Waiting for helm chart packaging fix before merging.

**Comment by MarcelMue** [comment]
Please rebase / resolve conflicts to see if we are good now 🙇‍♂️

**Comment by CoderTH** [comment]
> Please rebase / resolve conflicts to see if we are good now 🙇‍♂️

ok, done please help me run ci again

**Comment by CoderTH** [comment]
@thcdrt @MarcelMue It look like ci pipeline is ok now

**Review by MarcelMue — APPROVED** [review]

**Comment by CoderTH** [comment]
Thanks for your review and support 🙇 @thcdrt @MarcelMue 
（But there doesn't seem to be an auto-merge

**Comment by CoderTH** [comment]
> I can merge - thanks for your help!
> 
> I will create a follow up issue to check if we need to do some more testing later on.

Ok, What can I do for you if needed

**Comment by MarcelMue** [comment]
Please check if everything in your projects which imports harbor operator works correctly now :)

I think we mostly need some more test cases for current and new functionality, but there is nothing I can point you to right now

**Pull request merged**
