### PR TITLE
Docs/tutorials registry

### PR DESCRIPTION
**Pull request by holyhope**

### CODE REVIEW

**Comment by steven-zou** [comment]
@holyhope 

`md` doc lint failed.

I saw you removed the external DB, Redis, and storage configuration doc links, will you add them in other sections?

**Comment by holyhope** [comment]
It is not yet planed. I saw that:

- This documentation was outdated and was here because CRD were not strongly typed.
- CRD documentation explains well all storage definitions.
- The documentation I removed did not bring anything more than the CRD documentation.

Do not you agree?

**Comment by steven-zou** [comment]
> It is not yet planed. I saw that:
> 
> * This documentation was outdated and was here because CRD were not strongly typed.
> * CRD documentation explains well all storage definitions.
> * The documentation I removed did not bring anything more than the CRD documentation.
> 
> Do not you agree?

@holyhope 

Ok, I got your plan. I agree. For better doc navigation experiences, I can create some doc links to point to the right section of the CRD spec doc for guiding users on how to customize the external services.

One more thing, maybe we also need to add comments on the CRD about the secret data of psql secret and redis secret?

**Review by steven-zou — APPROVED** [review]
LGTM

**Review by heww — APPROVED** [review]

**Comment by steven-zou** [comment]
> > It is not yet planed. I saw that:
> > 
> > * This documentation was outdated and was here because CRD were not strongly typed.
> > * CRD documentation explains well all storage definitions.
> > * The documentation I removed did not bring anything more than the CRD documentation.
> > 
> > Do not you agree?
> 
> @holyhope
> 
> Ok, I got your plan. I agree. For better doc navigation experiences, I can create some doc links to point to the right section of the CRD spec doc for guiding users on how to customize the external services.
> 
> One more thing, maybe we also need to add comments on the CRD about the secret data of psql secret and redis secret?
@holyhope 

I’ll merge this PR and append some info about the data of psql secret and redis secret as well as related links pointing to the right content sections located at CRD spec doc.

**Pull request merged**
