### PR TITLE
upgrade minio operator to v4.4.9

### PR DESCRIPTION
**Pull request by soulseen**
Signed-off-by: soulseen <zhuxiaoyang1996@gmail.com>

### CODE REVIEW

**Comment by yxxhero** [comment]
@soulseen please fix ci error.

**Comment by yxxhero** [comment]
unittest need to fix.

**Comment by bitsf** [comment]
`charts/harbor-operator/Chart.yaml` also need change

**Review by bitsf — APPROVED** [review]

**Review by yxxhero — APPROVED** [review]
/lgtm

**Pull request merged**
