### PR TITLE
refine the NOTES.txt

### PR DESCRIPTION
**Pull request by panpan0000**
previous NOTES maybe comes from harbor helm, not for harbor-operator. 

so I fix it to avoid confusion.

### CODE REVIEW

**Review by bitsf — APPROVED** [review]

**Review by thcdrt — CHANGES_REQUESTED** [review]

**Comment by bitsf** [comment]
@panpan0000 are you going to fix above review?

**Comment by panpan0000** [comment]
aha, such a long Chinese New Year. Sorry for long inactivity . 
just fixed.

**Comment by panpan0000** [comment]
just rebased the latest master(main) branch, will have to kick off the CI test again.. T_T

**Comment by panpan0000** [comment]
I've no idea why CI "Generated files are up to date (pull_request) " test still failed after I rebase the latest main.....

**Comment by thcdrt** [comment]
Tests are broken on main since postgresql helm chart has been deleted on bitnami side, we started to investigate with @MarcelMue but we need to continue, sorry for this.

**Comment by panpan0000** [comment]
Thanks @MarcelMue , if anything I could do ,please let me know

**Comment by panpan0000** [comment]
/retest

seems e2e enviroment issue.

**Comment by OrlinVasilev** [comment]
@panpan0000 congrats on your first merged PR :)) Welcome to the club :)))

**Pull request merged**
