### PR TITLE
Fix make dev-tools on M1 macs

### PR DESCRIPTION
**Pull request by jake-ciolek**
Neither golangci-lint 1.33.0 nor kustomize 3.8.7 provide darwin/arm64 releases.

Bump golangci-lint to 1.37.1 and kustomize to 4.2.0 as these are the oldest versions with darwin/arm64 releases.

I have run make test with new golangci-lint/kustomize binaries on a linux box and they all passed.

Signed-off-by: Jakub Ciolek <jakub@ciolek.dev>

### CODE REVIEW

**Review by cndoit18 — APPROVED** [review]
LGTM

**Comment by steven-zou** [comment]
@jake-ciolek Thanks for the contributions! Please fix the CI failures.

**Comment by jake-ciolek** [comment]
Fixed go-lint warnings and the reason for failing generated-diff-test test.

**Comment by chlins** [comment]
@jake-ciolek Please rebase and resolve the conflicts.

**Comment by jake-ciolek** [comment]
Rebased and fixed some typos :)

**Comment by bitsf** [comment]
also fixed by https://github.com/goharbor/harbor-operator/pull/882

**Pull request closed without merging**
