### PR TITLE
fix(ingress): resolve 413(Too Large Entity) error when push large image.

### LINKED ISSUE #63: The registry configuration `redirect: disable: false` should be exposed at the harbor CR spec
Found issues in the cluster-operator: https://github.com/goharbor/harbor-cluster-operator/issues/118

registry configuration references: https://docs.docker.com/registry/configuration/

similar configurations in helm chart:  https://github.com/goharbor/harbor-helm/blob/fad6918c0fe3ca916d0948b98d433f6bffc96035/values.yaml#L243

### PR DESCRIPTION
**Pull request by wangcanfengxs**
add annotation to unlimit the size of http request body.

CLOSES #63

### CODE REVIEW

**Comment by steven-zou** [comment]
@holyhope 

Could you please take a look? Thanks!

**Comment by steven-zou** [comment]
@holyhope 

It seems the failed cases need to be revised, some configurations are not fresh now? Any suggestions?

**Comment by holyhope** [comment]
> It seems the failed cases need to be revised, some configurations are not fresh now? Any suggestions?

Fyi I configured the ingress controller itself to have this behaviour. So tests will pass when installing the ingress controller with the make target. We could remove this helm value from the make target?

**Comment by steven-zou** [comment]
> > It seems the failed cases need to be revised, some configurations are not fresh now? Any suggestions?
> 
> Fyi I configured the ingress controller itself to have this behaviour. So tests will pass when installing the ingress controller with the make target. We could remove this helm value from the make target?

@holyhope 

What's the purpose for introducing this make target?  What functions do you want to use this make target to test?

**Pull request merged**
